convoy-nfs:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.scheduler.global: 'true'
  privileged: true
  pid: host
  volumes:
    - /lib/modules:/lib/modules:ro
    - /proc:/host/proc
    - /var/run:/host/var/run
    - /etc/docker/plugins:/etc/docker/plugins
  image: youyun-private-harbor:9080/library/convoy-agent:v0.7.0
  command: volume-agent-nfs

convoy-nfs-storagepool:
  labels:
    io.rancher.container.create_agent: 'true'
  image: youyun-private-harbor:9080/library/convoy-agent:v0.7.0
  volumes:
    - /var/run:/host/var/run
  command: storagepool-agent
