version: '2'
services:
  healthcheck:
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
    image: youyun-private-harbor:9080/library/healthcheck:v0.3.1
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
