version: '2'
services:
  scheduler:
    image: youyun-private-harbor:9080/library/scheduler:v0.8.2
    command: scheduler
    environment:
        RANCHER_DEBUG: '${RANCHER_DEBUG}'
    labels:
        io.rancher.container.create_agent: "true"
        io.rancher.container.agent_service.scheduling: "true"
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
